Attribute VB_Name = "ModuleSecurityAllowlist"
'MIT License

'Copyright (c) 2021 - 2026 iappyx

'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:

'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.

'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.

'AUTO-GENERATED - do not edit by hand.

Option Explicit

Private AllowlistCache As Object

Private Function GetAllowlist() As Object
    If AllowlistCache Is Nothing Then Set AllowlistCache = BuildAllowlist()
    Set GetAllowlist = AllowlistCache
End Function

Private Function BuildAllowlist() As Object
    Dim d As Object
    Set d = CreateObject("Scripting.Dictionary")
    d.CompareMode = 1
    d.Add "addhighlight", Empty
    d.Add "addselectedslidestolibraryfile", Empty
    d.Add "addspecialslidetag", Empty
    d.Add "addtag", Empty
    d.Add "allemojis", Empty
    d.Add "anonymizeshapewithloremipsum", Empty
    d.Add "anonymizewithloremipsum", Empty
    d.Add "applycustom1", Empty
    d.Add "applycustom2", Empty
    d.Add "applycustom3", Empty
    d.Add "applycustom4", Empty
    d.Add "applycustom5", Empty
    d.Add "applyh1", Empty
    d.Add "applyh2", Empty
    d.Add "applyh3", Empty
    d.Add "applyhangingindentchange", Empty
    d.Add "applyparagraph", Empty
    d.Add "applypixelcolortofill", Empty
    d.Add "applypixelcolortooutline", Empty
    d.Add "applyquote", Empty
    d.Add "applysamecroptoselectedimages", Empty
    d.Add "applytextformatting", Empty
    d.Add "applytextstyle", Empty
    d.Add "arrangeshapes", Empty
    d.Add "averagefivepointstars", Empty
    d.Add "averageharveyball", Empty
    d.Add "averageragstatus", Empty
    d.Add "bringforward", Empty
    d.Add "bringtofront", Empty
    d.Add "calculateaveragefontsizebyparagraph", Empty
    d.Add "calltoslidescopesform", Empty
    d.Add "canfix", Empty
    d.Add "changeshapespellchecklanguage", Empty
    d.Add "changespellchecklanguage", Empty
    d.Add "checkifapplescriptpluginisinstalled", Empty
    d.Add "cleanupaddslidenumbers", Empty
    d.Add "cleanuphideandmoveselectedslides", Empty
    d.Add "cleanupremoveanimationsfromallslides", Empty
    d.Add "cleanupremovecommentsfromallslides", Empty
    d.Add "cleanupremovehiddenslides", Empty
    d.Add "cleanupremoveslideshowtransitionsfromallslides", Empty
    d.Add "cleanupremovespeakernotesfromallslides", Empty
    d.Add "cleanupremoveunusedmasterslides", Empty
    d.Add "clearhighlight", Empty
    d.Add "colorboldtextcolorautomatically", Empty
    d.Add "colorboldtextcolorpicker", Empty
    d.Add "colordialog", Empty
    d.Add "connectrectangleshapes", Empty
    d.Add "connectrectangleshapesbottomtotop", Empty
    d.Add "connectrectangleshapeslefttoright", Empty
    d.Add "connectrectangleshapesrighttoleft", Empty
    d.Add "connectrectangleshapestoptobottom", Empty
    d.Add "convertallcommentstostickynotes", Empty
    d.Add "convertallslidestopictures", Empty
    d.Add "convertcommentstostickynotes", Empty
    d.Add "convertselectedslidestopictures", Empty
    d.Add "convertshapestotable", Empty
    d.Add "convertslidestopictures", Empty
    d.Add "converttabletoshapes", Empty
    d.Add "converttexttoshapes", Empty
    d.Add "copyborders", Empty
    d.Add "copyposition", Empty
    d.Add "copyselectedshapetoallmasters", Empty
    d.Add "copyselectedshapetomaster", Empty
    d.Add "copyselectedshapetousedmasters", Empty
    d.Add "copyselectedtexttonewelement", Empty
    d.Add "copyshapetomultipleslides", Empty
    d.Add "copyslidenotestoclipboard", Empty
    d.Add "copyslidenotestoclipboardonly", Empty
    d.Add "copyslidenotestoword", Empty
    d.Add "copystorylinetoclipboard", Empty
    d.Add "copystorylinetoclipboardonly", Empty
    d.Add "copystorylinetoword", Empty
    d.Add "copytoclipboard", Empty
    d.Add "countcaptions", Empty
    d.Add "counttotallines", Empty
    d.Add "createagendapages", Empty
    d.Add "createorupdatemasteragenda", Empty
    d.Add "createstyleshape", Empty
    d.Add "createstylesheetlayout", Empty
    d.Add "createstylesheetonallmasters", Empty
    d.Add "createstylesheetonmaster", Empty
    d.Add "cropimagebydominantedgecolor", Empty
    d.Add "cropselectedimagebydominantedgecolor", Empty
    d.Add "decreasehangingindent", Empty
    d.Add "deleteallinstrumentasettings", Empty
    d.Add "deletealltags", Empty
    d.Add "deletestampsonallslides", Empty
    d.Add "deletestampsonslide", Empty
    d.Add "deletestickynotesonallslides", Empty
    d.Add "deletestickynotesonslide", Empty
    d.Add "deletetag", Empty
    d.Add "deletetaggedshapes", Empty
    d.Add "emailselectedslides", Empty
    d.Add "emailselectedslidesaspdf", Empty
    d.Add "emojigallery_getitemcount", Empty
    d.Add "emojigallery_getitemheight", Empty
    d.Add "emojigallery_getitemid", Empty
    d.Add "emojigallery_getitemimage", Empty
    d.Add "emojigallery_getitemlabel", Empty
    d.Add "emojigallery_getitemscreentip", Empty
    d.Add "emojigallery_getitemwidth", Empty
    d.Add "emojigallery_onaction", Empty
    d.Add "enablewhenexactlyoneshape", Empty
    d.Add "enablewhenintable", Empty
    d.Add "enablewhenmultipleshapesselected", Empty
    d.Add "enablewhenshapeortext", Empty
    d.Add "enablewhenshapesselected", Empty
    d.Add "enablewhenslidesselected", Empty
    d.Add "enablewhentextselected", Empty
    d.Add "excelfullfilemailmerge", Empty
    d.Add "excelmailmerge", Empty
    d.Add "executefeature", Empty
    d.Add "exportstylestopptx", Empty
    d.Add "findmergefields", Empty
    d.Add "findstylesheet", Empty
    d.Add "fixallincategory", Empty
    d.Add "fixissue", Empty
    d.Add "generatecrossslidestepscounter", Empty
    d.Add "generateemoji", Empty
    d.Add "generatefivepointstars", Empty
    d.Add "generatefivepointstars05", Empty
    d.Add "generatefivepointstars10", Empty
    d.Add "generatefivepointstars15", Empty
    d.Add "generatefivepointstars20", Empty
    d.Add "generatefivepointstars25", Empty
    d.Add "generatefivepointstars30", Empty
    d.Add "generatefivepointstars35", Empty
    d.Add "generatefivepointstars40", Empty
    d.Add "generatefivepointstars45", Empty
    d.Add "generatefivepointstars50", Empty
    d.Add "generateharveyball10", Empty
    d.Add "generateharveyball100", Empty
    d.Add "generateharveyball20", Empty
    d.Add "generateharveyball25", Empty
    d.Add "generateharveyball30", Empty
    d.Add "generateharveyball33", Empty
    d.Add "generateharveyball40", Empty
    d.Add "generateharveyball50", Empty
    d.Add "generateharveyball60", Empty
    d.Add "generateharveyball67", Empty
    d.Add "generateharveyball70", Empty
    d.Add "generateharveyball75", Empty
    d.Add "generateharveyball80", Empty
    d.Add "generateharveyball90", Empty
    d.Add "generateharveyballcustom", Empty
    d.Add "generateharveyballpercent", Empty
    d.Add "generateragstatus", Empty
    d.Add "generateragstatusamber", Empty
    d.Add "generateragstatusgreen", Empty
    d.Add "generateragstatusred", Empty
    d.Add "generatestamp", Empty
    d.Add "generatestampconfidential", Empty
    d.Add "generatestampdonotdistribute", Empty
    d.Add "generatestampdraft", Empty
    d.Add "generatestampnew", Empty
    d.Add "generatestamptoappendix", Empty
    d.Add "generatestamptoberemoved", Empty
    d.Add "generatestampupdated", Empty
    d.Add "generatestepscounter", Empty
    d.Add "generatestickynote", Empty
    d.Add "getcurrentslidemaster", Empty
    d.Add "getdecimalseperator", Empty
    d.Add "getdefaultconfig", Empty
    d.Add "getfeaturebyindex", Empty
    d.Add "getfeaturecount", Empty
    d.Add "getissue", Empty
    d.Add "getissuecount", Empty
    d.Add "getloremipsum", Empty
    d.Add "getrealheight", Empty
    d.Add "getrealleft", Empty
    d.Add "getrealtop", Empty
    d.Add "getrealwidth", Empty
    d.Add "getrulerunit", Empty
    d.Add "getrulerunitconversion", Empty
    d.Add "groupshapesbycolumns", Empty
    d.Add "groupshapesbyrows", Empty
    d.Add "hidetagsonslide", Empty
    d.Add "importheadersfromexcel", Empty
    d.Add "importstylesfrompptx", Empty
    d.Add "increasehangingindent", Empty
    d.Add "increaseshapetransparency", Empty
    d.Add "initialisesetpositionappeventhandler", Empty
    d.Add "initialize", Empty
    d.Add "initializeemojinames", Empty
    d.Add "initializeemojis", Empty
    d.Add "initializeemojis2", Empty
    d.Add "insertcaption", Empty
    d.Add "insertcolumnkeepothercolumnwidths", Empty
    d.Add "insertcolumntoleftkeepothercolumnwidths", Empty
    d.Add "insertcolumntorightkeepothercolumnwidths", Empty
    d.Add "insertlegend", Empty
    d.Add "insertlegendcirclehorizontalfive", Empty
    d.Add "insertlegendcirclehorizontalten", Empty
    d.Add "insertlegendcirclehorizontalthree", Empty
    d.Add "insertlegendcircleverticalfive", Empty
    d.Add "insertlegendcircleverticalten", Empty
    d.Add "insertlegendcircleverticalthree", Empty
    d.Add "insertlegendcustom", Empty
    d.Add "insertlegendsquarehorizontalfive", Empty
    d.Add "insertlegendsquarehorizontalten", Empty
    d.Add "insertlegendsquarehorizontalthree", Empty
    d.Add "insertlegendsquareverticalfive", Empty
    d.Add "insertlegendsquareverticalten", Empty
    d.Add "insertlegendsquareverticalthree", Empty
    d.Add "insertmergefield", Empty
    d.Add "insertprocesssmartart", Empty
    d.Add "insertqrcode", Empty
    d.Add "insertwatermarkandconvertslidestopictures", Empty
    d.Add "instrumentagetvisible", Empty
    d.Add "instrumentagetvisiblemultitabview", Empty
    d.Add "instrumentagetvisibleonetabview", Empty
    d.Add "instrumentainitialize", Empty
    d.Add "instrumentarefresh", Empty
    d.Add "isallowedprocedure", Empty
    d.Add "iscr_applyproperty", Empty
    d.Add "iscr_applyset", Empty
    d.Add "iscr_applysetvar", Empty
    d.Add "iscr_computenumber", Empty
    d.Add "iscr_computetext", Empty
    d.Add "iscr_evalcondition", Empty
    d.Add "iscr_evalkeywordexpr", Empty
    d.Add "iscr_executedelete", Empty
    d.Add "iscr_executeduplicate", Empty
    d.Add "iscr_executegroup", Empty
    d.Add "iscr_executeif", Empty
    d.Add "iscr_executeinsert", Empty
    d.Add "iscr_executeinsertconnector", Empty
    d.Add "iscr_executeinsertline", Empty
    d.Add "iscr_executerepeat", Empty
    d.Add "iscr_executerotate", Empty
    d.Add "iscr_executeselect", Empty
    d.Add "iscr_executeungroup", Empty
    d.Add "iscr_executeuseselection", Empty
    d.Add "iscr_extractquotedvalue", Empty
    d.Add "iscr_findblockend", Empty
    d.Add "iscr_findcommaoutsideparens", Empty
    d.Add "iscr_getvar", Empty
    d.Add "iscr_getvarstring", Empty
    d.Add "iscr_hextorgb", Empty
    d.Add "iscr_invokecommand", Empty
    d.Add "iscr_isalphanum", Empty
    d.Add "iscr_isifcommand", Empty
    d.Add "iscr_isnumericexpr", Empty
    d.Add "iscr_log", Empty
    d.Add "iscr_parsecondand", Empty
    d.Add "iscr_parsecondatom", Empty
    d.Add "iscr_parsecondnot", Empty
    d.Add "iscr_parsecondor", Empty
    d.Add "iscr_parsekeywordstringexpr", Empty
    d.Add "iscr_readexpressionaddsub", Empty
    d.Add "iscr_readexpressionmuldiv", Empty
    d.Add "iscr_readexpressionprimary", Empty
    d.Add "iscr_readexpressionunary", Empty
    d.Add "iscr_replacewholeword", Empty
    d.Add "iscr_replacewholewordoutsidequotes", Empty
    d.Add "iscr_resolveselectcriteria", Empty
    d.Add "iscr_runblock", Empty
    d.Add "iscr_setvar", Empty
    d.Add "iscr_setvarstring", Empty
    d.Add "iscr_shapematchescriteria", Empty
    d.Add "iscr_shapematchestype", Empty
    d.Add "iscr_shapenameexists", Empty
    d.Add "iscr_splitcondon", Empty
    d.Add "iscr_splitexpression", Empty
    d.Add "iscr_splitstringexpr", Empty
    d.Add "iscr_substitutestringvars", Empty
    d.Add "iscr_substitutevars", Empty
    d.Add "iscr_syncselectiontopowerpoint", Empty
    d.Add "iscr_varexists", Empty
    d.Add "layoutisused", Empty
    d.Add "linespacingremove", Empty
    d.Add "lockallshapesonallslides", Empty
    d.Add "lockaspectratiotoggleselectedshapes", Empty
    d.Add "locktoggleallshapesonallslides", Empty
    d.Add "locktoggleselectedshapes", Empty
    d.Add "macfiledialog", Empty
    d.Add "macsaveasdialog", Empty
    d.Add "manualmailmerge", Empty
    d.Add "movecolumn", Empty
    d.Add "moverow", Empty
    d.Add "moveselectedroworcolumn", Empty
    d.Add "moveselectedshapetoallmasters", Empty
    d.Add "moveselectedshapetomaster", Empty
    d.Add "moveselectedshapetousedmasters", Empty
    d.Add "moveselectedtexttonewelement", Empty
    d.Add "movestampsoffallslides", Empty
    d.Add "movestampsoffslide", Empty
    d.Add "movestampsonallslides", Empty
    d.Add "movestampsonslide", Empty
    d.Add "movestickynotesoffallslides", Empty
    d.Add "movestickynotesoffslide", Empty
    d.Add "movestickynotesonallslides", Empty
    d.Add "movestickynotesonslide", Empty
    d.Add "movetablecolumnleft", Empty
    d.Add "movetablecolumnleftignoreborders", Empty
    d.Add "movetablecolumnlefttextonly", Empty
    d.Add "movetablecolumnright", Empty
    d.Add "movetablecolumnrightignoreborders", Empty
    d.Add "movetablecolumnrighttextonly", Empty
    d.Add "movetablerowdown", Empty
    d.Add "movetablerowdownignoreborders", Empty
    d.Add "movetablerowdowntextonly", Empty
    d.Add "movetablerowup", Empty
    d.Add "movetablerowupignoreborders", Empty
    d.Add "movetablerowuptextonly", Empty
    d.Add "newelementfromselectedtext", Empty
    d.Add "objectsalignbottoms", Empty
    d.Add "objectsaligncenters", Empty
    d.Add "objectsalignlefts", Empty
    d.Add "objectsalignmiddles", Empty
    d.Add "objectsalignrights", Empty
    d.Add "objectsaligntops", Empty
    d.Add "objectsaligntotable", Empty
    d.Add "objectsaligntotablecolumn", Empty
    d.Add "objectsaligntotablerow", Empty
    d.Add "objectsautosizenone", Empty
    d.Add "objectsautosizeshapetofittext", Empty
    d.Add "objectsautosizetexttofitshape", Empty
    d.Add "objectsclonedown", Empty
    d.Add "objectscloneright", Empty
    d.Add "objectscopyroundedcorner", Empty
    d.Add "objectscopyshapetypeandadjustments", Empty
    d.Add "objectsdecreaselinespacing", Empty
    d.Add "objectsdecreaselinespacingbeforeandafter", Empty
    d.Add "objectsdecreasespacinghorizontal", Empty
    d.Add "objectsdecreasespacingvertical", Empty
    d.Add "objectsdistributehorizontally", Empty
    d.Add "objectsdistributevertically", Empty
    d.Add "objectsfliphorizontal", Empty
    d.Add "objectsflipvertical", Empty
    d.Add "objectsincreaselinespacing", Empty
    d.Add "objectsincreaselinespacingbeforeandafter", Empty
    d.Add "objectsincreasespacinghorizontal", Empty
    d.Add "objectsincreasespacingvertical", Empty
    d.Add "objectsindentationloop", Empty
    d.Add "objectslinespacingbeforeandafterloop", Empty
    d.Add "objectslinespacingloop", Empty
    d.Add "objectsmarginsdecrease", Empty
    d.Add "objectsmarginsincrease", Empty
    d.Add "objectsmarginsloop", Empty
    d.Add "objectsmarginstozero", Empty
    d.Add "objectsquicksorttoplefttobottomright", Empty
    d.Add "objectsremovehyperlinks", Empty
    d.Add "objectsremovehyperlinksloop", Empty
    d.Add "objectsremovespacinghorizontal", Empty
    d.Add "objectsremovespacinghorizontalright", Empty
    d.Add "objectsremovespacingvertical", Empty
    d.Add "objectsremovespacingverticaldown", Empty
    d.Add "objectsremovetext", Empty
    d.Add "objectsremovetextloop", Empty
    d.Add "objectsrotateclockwise", Empty
    d.Add "objectsrotatecounterclockwise", Empty
    d.Add "objectssameheight", Empty
    d.Add "objectssameheightandwidth", Empty
    d.Add "objectssamewidth", Empty
    d.Add "objectsselectbysamefillandlinecolor", Empty
    d.Add "objectsselectbysamefillcolor", Empty
    d.Add "objectsselectbysameheight", Empty
    d.Add "objectsselectbysamelinecolor", Empty
    d.Add "objectsselectbysametype", Empty
    d.Add "objectsselectbysamewidth", Empty
    d.Add "objectsselectbysamewidthandheight", Empty
    d.Add "objectssizetonarrowest", Empty
    d.Add "objectssizetoshortest", Empty
    d.Add "objectssizetotallest", Empty
    d.Add "objectssizetowidest", Empty
    d.Add "objectssortbybottomposition", Empty
    d.Add "objectssortbyleftposition", Empty
    d.Add "objectssortbyrightposition", Empty
    d.Add "objectssortbytopposition", Empty
    d.Add "objectsstretchbottom", Empty
    d.Add "objectsstretchbottomshapetop", Empty
    d.Add "objectsstretchleft", Empty
    d.Add "objectsstretchleftshaperight", Empty
    d.Add "objectsstretchright", Empty
    d.Add "objectsstretchrightshapeleft", Empty
    d.Add "objectsstretchtop", Empty
    d.Add "objectsstretchtopshapebottom", Empty
    d.Add "objectsswapposition", Empty
    d.Add "objectsswappositioncentered", Empty
    d.Add "objectsswaptext", Empty
    d.Add "objectsswaptextnoformatting", Empty
    d.Add "objectstextaddperiods", Empty
    d.Add "objectstextcolorbold", Empty
    d.Add "objectstextdeletestrikethrough", Empty
    d.Add "objectstextinsertspecialcharacter", Empty
    d.Add "objectstextmerge", Empty
    d.Add "objectstextremoveperiods", Empty
    d.Add "objectstextsplitbyparagraph", Empty
    d.Add "objectstexttogglecase", Empty
    d.Add "objectstextwordwraptoggle", Empty
    d.Add "objectstextwordwraptoggleloop", Empty
    d.Add "objectstoggleautosize", Empty
    d.Add "objectstoggleautosizeloop", Empty
    d.Add "openslidelibraryfile", Empty
    d.Add "openstylesheet", Empty
    d.Add "optimizetableheight10iterations", Empty
    d.Add "optimizetableheight20iterations", Empty
    d.Add "optimizetableheight3iterations", Empty
    d.Add "optimizetableheight5iterations", Empty
    d.Add "optimizetableheightbycontent", Empty
    d.Add "optimizetableheightquick", Empty
    d.Add "optimizetablemultipleruns", Empty
    d.Add "paragraphspacingremove", Empty
    d.Add "pasteposition", Empty
    d.Add "pastepositionanddimensions", Empty
    d.Add "pastestorylineinselectedshape", Empty
    d.Add "pauseformilliseconds", Empty
    d.Add "picturecroptoslide", Empty
    d.Add "populateslidetagvaluelistbox", Empty
    d.Add "quicksorttoplefttobottomright", Empty
    d.Add "recountcaptions", Empty
    d.Add "rectifylines", Empty
    d.Add "removeallinstrumentastyletags", Empty
    d.Add "removeduplicates", Empty
    d.Add "removeinstrumentastylesheet", Empty
    d.Add "removestylesheetsfromallmasters", Empty
    d.Add "renumbercaptions", Empty
    d.Add "repaintthumbnails", Empty
    d.Add "replacecolor", Empty
    d.Add "replacecolorinselectedshapes", Empty
    d.Add "replacemergefields", Empty
    d.Add "resethangingindent", Empty
    d.Add "resizeandspaceevenhorizontal", Empty
    d.Add "resizeandspaceevenhorizontalpreservefirst", Empty
    d.Add "resizeandspaceevenhorizontalpreservelast", Empty
    d.Add "resizeandspaceevenly", Empty
    d.Add "resizeandspaceevenvertical", Empty
    d.Add "resizeandspaceevenverticalpreservefirst", Empty
    d.Add "resizeandspaceevenverticalpreservelast", Empty
    d.Add "rgbtohex", Empty
    d.Add "ribbonobjectgetimage", Empty
    d.Add "runinstrumentascript", Empty
    d.Add "runslidegrader", Empty
    d.Add "sanitizeapplescriptpath", Empty
    d.Add "sanitizefilename", Empty
    d.Add "saveselectedslides", Empty
    d.Add "scanandmanagecolors", Empty
    d.Add "scancolorsinselectedshapes", Empty
    d.Add "scanselectedshapesonly", Empty
    d.Add "scriptpreset_getitemcount", Empty
    d.Add "scriptpreset_getitemid", Empty
    d.Add "scriptpreset_getitemlabel", Empty
    d.Add "scriptpreset_onaction", Empty
    d.Add "scriptpreset_run", Empty
    d.Add "searchfeatures", Empty
    d.Add "selectallcrossslidestepscounter", Empty
    d.Add "selectallstepscounter", Empty
    d.Add "selectslidesbystamp", Empty
    d.Add "selectslidesbytag", Empty
    d.Add "sendbackward", Empty
    d.Add "sendtoback", Empty
    d.Add "setprogress", Empty
    d.Add "setrealheight", Empty
    d.Add "setrealleft", Empty
    d.Add "setrealtop", Empty
    d.Add "setrealwidth", Empty
    d.Add "settransparency", Empty
    d.Add "shapesinsertbentarrow", Empty
    d.Add "shapesinsertcloudcallout", Empty
    d.Add "shapesinsertcurvedrightarrow", Empty
    d.Add "shapesinsertdownarrow", Empty
    d.Add "shapesinsertflowchartconnector", Empty
    d.Add "shapesinsertflowchartdecision", Empty
    d.Add "shapesinsertflowchartprocess", Empty
    d.Add "shapesinsertflowchartterminator", Empty
    d.Add "shapesinserthexagon", Empty
    d.Add "shapesinsertleftarrow", Empty
    d.Add "shapesinsertleftbrace", Empty
    d.Add "shapesinsertleftbracket", Empty
    d.Add "shapesinsertoctagon", Empty
    d.Add "shapesinsertoval", Empty
    d.Add "shapesinsertovalcallout", Empty
    d.Add "shapesinsertparallelogram", Empty
    d.Add "shapesinsertpentagon", Empty
    d.Add "shapesinsertrectangle", Empty
    d.Add "shapesinsertrightarrow", Empty
    d.Add "shapesinsertrightbrace", Empty
    d.Add "shapesinsertrightbracket", Empty
    d.Add "shapesinsertrighttriangle", Empty
    d.Add "shapesinsertroundedrectangle", Empty
    d.Add "shapesinsertroundedrectangularcallout", Empty
    d.Add "shapesinsertstar10", Empty
    d.Add "shapesinsertstar12", Empty
    d.Add "shapesinsertstar16", Empty
    d.Add "shapesinsertstar24", Empty
    d.Add "shapesinsertstar32", Empty
    d.Add "shapesinsertstar4", Empty
    d.Add "shapesinsertstar5", Empty
    d.Add "shapesinsertstar6", Empty
    d.Add "shapesinsertstar7", Empty
    d.Add "shapesinsertstar8", Empty
    d.Add "shapesinsertstraightarrow", Empty
    d.Add "shapesinsertstraightline", Empty
    d.Add "shapesinserttrapezoid", Empty
    d.Add "shapesinserttriangle", Empty
    d.Add "shapesinsertuparrow", Empty
    d.Add "shapesinsertwave", Empty
    d.Add "shapetomasterslide", Empty
    d.Add "showaboutdialog", Empty
    d.Add "showandcleanpresentationleveltags", Empty
    d.Add "showchangespellchecklanguageform", Empty
    d.Add "showcolors", Empty
    d.Add "showcustominsertlegend", Empty
    d.Add "showfeaturesearch", Empty
    d.Add "showformcopyshapetomultipleslides", Empty
    d.Add "showformmanagetags", Empty
    d.Add "showformselectslidesbytag", Empty
    d.Add "showpyramidbuilder", Empty
    d.Add "showscripteditor", Empty
    d.Add "showsettings", Empty
    d.Add "showslidegrader", Empty
    d.Add "showslidelibrary", Empty
    d.Add "showtagsonslide", Empty
    d.Add "splittablebycolumn", Empty
    d.Add "splittablebyrow", Empty
    d.Add "tablecolumndecreasegaps", Empty
    d.Add "tablecolumngaps", Empty
    d.Add "tablecolumngapseven", Empty
    d.Add "tablecolumngapsodd", Empty
    d.Add "tablecolumnincreasegaps", Empty
    d.Add "tablecolumnremovegaps", Empty
    d.Add "tabledistributecolumnswithgaps", Empty
    d.Add "tabledistributerowswithgaps", Empty
    d.Add "tablequickformat", Empty
    d.Add "tableremovebackgrounds", Empty
    d.Add "tableremoveborders", Empty
    d.Add "tablerowdecreasegaps", Empty
    d.Add "tablerowgaps", Empty
    d.Add "tablerowgapseven", Empty
    d.Add "tablerowgapsodd", Empty
    d.Add "tablerowincreasegaps", Empty
    d.Add "tablerowremovegaps", Empty
    d.Add "tablerowsum", Empty
    d.Add "tablesmarginsdecrease", Empty
    d.Add "tablesmarginsincrease", Empty
    d.Add "tablesmarginstozero", Empty
    d.Add "tablesum", Empty
    d.Add "tabletranspose", Empty
    d.Add "textbulletscrosses", Empty
    d.Add "textbulletsticks", Empty
    d.Add "textinsertcopyright", Empty
    d.Add "textinserteuro", Empty
    d.Add "textinsertnobreakspace", Empty
    d.Add "toggleallchildren", Empty
    d.Add "togglecategorychildren", Empty
    d.Add "togglecheckbox", Empty
    d.Add "unloadsetpositionappeventhandler", Empty
    d.Add "unlockallshapesonallslides", Empty
    d.Add "updatefullshapestyles", Empty
    d.Add "updatetaggedshapepositionanddimensions", Empty
    d.Add "urlencodestring", Empty
    Set BuildAllowlist = d
End Function
Public Function IsAllowedProcedure(procName As String) As Boolean
    Dim n As String
    n = procName
    Dim p As Integer
    p = InStr(n, ".")
    If p > 0 Then n = Mid(n, p + 1)
    IsAllowedProcedure = GetAllowlist().Exists(LCase(n))
End Function


