#!/bin/bash

# MIT License
# Copyright (c) 2021-2025 iappyx
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


PPAM_MAIN_FOLDER="$HOME/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/Instrumenta/"
PPAM_MAIN_DEST="$HOME/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/Instrumenta/InstrumentaPowerpointToolbar.ppam"
PPAM_OPTIONAL_DEST="$HOME/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/Instrumenta/InstrumentaKeysHelper.ppam"
SCRIPT_MAIN_DEST="$HOME/Library/Application Scripts/com.microsoft.Powerpoint/InstrumentaAppleScriptPlugin.applescript"
SCRIPT_OPTIONAL_DEST="$HOME/Library/Application Scripts/com.microsoft.Powerpoint/InstrumentaKeys.applescript"

if [ -f "$PPAM_MAIN_DEST" ]; then
    rm -f "$PPAM_MAIN_DEST"
fi

if [ -f "$PPAM_OPTIONAL_DEST" ]; then
    rm -f "$PPAM_OPTIONAL_DEST"
fi

if [ -f "$SCRIPT_MAIN_DEST" ]; then
    rm -f "$SCRIPT_MAIN_DEST"
fi

if [ -f "$SCRIPT_OPTIONAL_DEST" ]; then
    rm -f "$SCRIPT_OPTIONAL_DEST"
fi

if [ -f "$PPAM_MAIN_FOLDER" ]; then
    rm -rf "$PPAM_MAIN_FOLDER"
fi


sudo pkgutil --forget com.iappyx.instrumenta
sudo pkgutil --forget com.iappyx.instrumentakeys
sudo pkgutil --forget com.iappyx.instrumenta.uninstall

echo "Instrumenta and Instrumenta Keys have been successfully uninstalled!"
